services:
  mysql:
    image: mysql:8
    container_name: member-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${CONTAINER_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - external-net

  member-service:
    image: ${DOCKER_IMAGE}:dev
    container_name: ${APPLICATION_NAME}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    env_file:
      - .env
    networks:
      - external-net
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  external-net:
    external: true
    name: ${MMB_DOCKER_NETWORK}
