server:
  port: ${APPLICATION_PORT:8082}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ${APPLICATION_NAME:mmb-member-service}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:demo_user}
    password: ${DB_PASSWORD:demo_password}
    url: jdbc:mysql://${DB_HOST:localhost}:${CONTAINER_DB_PORT:3306}/${DB_NAME:demo_db}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}

logging:
  level:
    root: ${LOG_ROOT_LEVEL:info}
    org.hibernate.orm.jdbc.bind: ${LOG_JPA_LEVEL:TRACE}
