server:
  port: ${MEMBER_SERVICE_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ${MEMBER_SERVICE_NAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MEMBER_SERVICE_DATASOURCE_URL}
    username: ${MEMBER_SERVICE_DATASOURCE_USERNAME}
    password: ${MEMBER_SERVICE_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    open-in-view: false
    show-sql: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: off
