name: DEV CD - Deploy to EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: mumulbo/member-service:dev

      - name: Create .env locally
        run: |
          echo "현재 경로는 $(pwd)입니다."
          echo "APPLICATION_PORT=${{ vars.APPLICATION_PORT }}" > .env
          echo "APPLICATION_NAME=${{ vars.APPLICATION_NAME }}" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "CONTAINER_DB_PORT=${{ vars.CONTAINER_DB_PORT }}" >> .env
          echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
          echo "JPA_DDL_AUTO=${{ vars.JPA_DDL_AUTO }}" >> .env
          echo "JPA_FORMAT_SQL=${{ vars.JPA_FORMAT_SQL }}" >> .env
          echo "JPA_SHOW_SQL=${{ vars.JPA_SHOW_SQL }}" >> .env
          echo "LOG_ROOT_LEVEL=${{ vars.LOG_ROOT_LEVEL }}" >> .env
          echo "LOG_JPA_LEVEL=${{ vars.LOG_JPA_LEVEL }}" >> .env

      - name: Copy docker-compose.yml and .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            docker-compose.yml
            .env
          target: /home/ec2-user/deploy/member-service

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/deploy/member-service
            docker pull mumulbo/member-service:dev
            docker-compose down
            docker-compose up -d
